apiVersion: v1
kind: ConfigMap
metadata:
  name: env-cm-example
data:
  FOO: bar
---
apiVersion: v1
kind: Pod
metadata:
  name: env-cm-pod-example
spec:
  containers:
  - name: test-container
    image: k8s.gcr.io/busybox
    command:
    - /bin/sh
    - -c
    - while true; do echo $FOO; sleep 5; done
    env:
    - name: FOO
      valueFrom:
        configMapKeyRef:
          name: env-cm-example
          key: FOO
