apiVersion: v1
kind: Pod
metadata:
  name: grpcurl
spec:
  containers:
  - name: grpcurl
    image: docker.io/fullstorydev/grpcurl:v1.8.7-alpine
    command:
      - sleep
      - "infinity"
    imagePullPolicy: IfNotPresent
  restartPolicy: Always
