apiVersion: v1
kind: Pod
metadata:
  name: redisutils
spec:
  containers:
  - name: redisutils
    image: redis:6.2.8
    command:
      - sleep
      - "infinity"
    imagePullPolicy: IfNotPresent
  restartPolicy: Always
