apiVersion: v1
kind: Pod
metadata:
  name: util-ncat
spec:
  containers:
  - name: ncat-centos
    image: docker.io/tafthorne/ncat-centos
    command:
      - sleep
      - "infinity"
    imagePullPolicy: IfNotPresent
  restartPolicy: Always
