apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rolebinding-example
  namespace: default
subjects:
- kind: ServiceAccount
  name: sa-example
  apiGroup: ""
roleRef:
  kind: Role
  name: role-example
  apiGroup: rbac.authorization.k8s.io
