apiVersion: apps/v1
kind: Deployment
metadata:
  name: hpa-hname-pods
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: echo-hname
        image: sysnet4admin/echo-hname
        resources:
          requests:
            cpu: "10m"
          limits:
            cpu: "50m"
