apiVersion: apps/v1
kind: Deployment
metadata:
  name: using-nfs-pvc
spec:
  replicas: 3
  selector:
    matchLabels:
      app: using-nfs-pvc
  template:
    metadata:
      labels:
        app: using-nfs-pvc
    spec:
      containers:
      - name: audit-trail
        image: sysnet4admin/audit-trail
        volumeMounts:
        - name: nfs-vol
          mountPath: /audit
      volumes:
      - name: nfs-vol
        persistentVolumeClaim:
          claimName: pvc-nfs
