apiVersion: v1
kind: Service
metadata:
  labels:
    app: kibana
  name: kb-kibana-np
  namespace: default
spec:
  ports:
  - nodePort: 30561
    port: 5601
    protocol: TCP
    targetPort: 5601
  selector:
    app: kibana
    release: kb
  type: NodePort
