apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: using-nfs-pvc-sfs
spec:
  replicas: 3
  serviceName: sts-svc-domain #statefulset needs this for headless networking
  selector:
    matchLabels:
      app: using-nfs-pvc-sfs
  template:
    metadata:
      labels:
        app: using-nfs-pvc-sfs
    spec:
      containers:
      - name: audit-trail
        image: sysnet4admin/audit-trail
