# Example of nginx statefulset
#   Source: https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/
apiVersion: v1
kind: Service
metadata:
  name: nginx-sfs-svc
  labels:
    app: nginx-sfs-svc
spec:
  ports:
  - port: 80
    name: web
  #clusterIP: None
  type: NodePort # Use NodePort for convenience
  selector:
    app: nginx-sfs
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nginx-sfs
spec:
  selector:
    matchLabels:
      app: nginx-sfs # has to match .spec.template.metadata.labels
  serviceName: "nginx"
  replicas: 3 # by default is 1
  #minReadySeconds: 10 # by default is 0
  template:
    metadata:
      labels:
        app: nginx-sfs # has to match .spec.selector.matchLabels
    spec:
      #terminationGracePeriodSeconds: 10
      containers:
      - name: nginx
        image: k8s.gcr.io/nginx-slim:0.8
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - name: www
          mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "nfs-client" # Use nfs-subdir-external-provisioner's default storage class name
      resources:
        requests:
          storage: 100Mi # Lessen the size from 1Gi to 100Mi
