apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-index-html
data:
  index.html: |
    <h1>HEADING 1</h1>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.15.12
        volumeMounts:
          - mountPath: /usr/share/nginx/html
            name: nginx-index-html
      volumes:
        - name: nginx-index-html
          configMap:
            name: nginx-index-html
            items:
              - key: "index.html"
                path: "index.html"
###
# FOR DEMONSTRATE, UNCOMMENT THE BELOW:
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: nginx
# spec:
#   selector:
#     app: nginx
#   ports:
#     - port: 80
# ---
# apiVersion: v1
# kind: Pod
# metadata:
#   name: curl
# spec:
#   containers:
#   - name: curl
#     image: docker.io/curlimages/curl:7.86.0
#     command:
#       - sleep
#       - "infinity"
#     imagePullPolicy: IfNotPresent
#   restartPolicy: Always
###
