---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: registry-images
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  storageClassName: local-mnt
  local:
    path: /mnt/nfs_shared/registry-images
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - k8s-m1
          - k8s-m2
          - k8s-m3
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: registry-image-volume-claim
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: local-mnt
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: registry
spec:
  selector:
    app: registry
  ports:
  - name: http
    protocol: TCP
    port: 5000
    targetPort: 5000
    nodePort: 30303
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry
  labels:
    app: registry
spec:
  replicas: 3
  selector:
    matchLabels:
      app: registry
  template:
    metadata:
      labels:
        app: registry
    spec:
      containers:
      - image: docker.io/library/registry:2
        name: registry
        volumeMounts:
        - name: images
          mountPath: /var/lib/registry
      volumes:
      - name: images
        persistentVolumeClaim:
          claimName: registry-image-volume-claim
