apiVersion: v1
kind: Pod
metadata:
  name: alpine
  labels:
    app: alpine
spec:
  containers:
  - image: docker.io/library/alpine:3.15
    imagePullPolicy: IfNotPresent
    name: alpine
    args:
    - /bin/sh
    - -c
    - while true; do sleep 3600; done
