apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: gf
    app.kubernetes.io/name: grafana
    app.kubernetes.io/version: 8.4.6
  name: gf-grafana-np
  namespace: default
spec:
  ports:
  - name: gs-grafana-np
    nodePort: 30030
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app.kubernetes.io/instance: gf
    app.kubernetes.io/name: grafana
  type: NodePort
